package main

const gatherTemplate = `
// DO NOT EDIT!!!
// This code was generated by github.com/andrew-d/sleepywolf

package main

import (
	"os"

	"github.com/andrew-d/sleepywolf/gather"

	// This is the package we're introspecting
	"{{.ImportPath}}"
)

{{$pn := .PackageName}}

func main() {
	g := gather.NewInfoGatherer()
{{range .StructNames}}
	g.Register("{{.}}", &{{$pn}}.{{.}}{})
{{end}}
	g.Run(os.Stdout)
}
`
