package main

const gatherTemplate = `
// DO NOT EDIT!!!
// This code was generated by github.com/andrew-d/sleepywolf

package main

import (
	"os"

	"github.com/andrew-d/sleepywolf/gather"

	// This is the package we're introspecting
	target "{{.ImportPath}}"
)

func main() {
	g := gather.NewInfoGatherer()
{{range .StructNames}}
	g.Register("{{.}}", &target.{{.}}{})
{{end}}
	g.Run(os.Stdout)
}
`

const finalTemplate = `
// This code was generated by github.com/andrew-d/sleepywolf

package {{.PackageName}}

import (
	"net/http"

	"github.com/zenazn/goji/web"
)

{{define "BeforeFunc"}}
	{{with .}}
		{{if .Params | eq 3}}
		if !res.{{.Name}}(c, w, r) { return }
		{{else}}
		if !res.{{.Name}}(w, r) { return }
		{{end}}
	{{end}}
{{end}}

{{$prefix := .UrlPrefix}}

{{range .Structs}}
func Register{{.StructName}}(mux *web.Mux) {
	{{$struct := .}}

	{{range .Handlers}}
		handlerFor{{.Name}} := func(c web.C, w http.ResponseWriter, r *http.Request) {
			// Create a new instance of the struct.
			res := &{{$struct.StructName}}{}

			{{if HasBeforeType .Name "BeforeAll"}}{{template "BeforeFunc" $struct.BeforeAll}}{{end}}
			{{if HasBeforeType .Name "BeforeAll"}}{{template "BeforeFunc" $struct.BeforeOne}}{{end}}
			{{if HasBeforeType .Name "BeforeAll"}}{{template "BeforeFunc" $struct.BeforeMany}}{{end}}

			{{if .Params | eq 3}}
				res.{{.Name}}(c, w, r)
			{{else}}
				res.{{.Name}}(w, r)
			{{end}}
		}
		mux.{{RegisterFuncFor .Name}}("{{$prefix}}/{{UrlFor $struct.StructName .Name}}", handlerFor{{.Name}})
	{{end}}
}
{{end}}
`
